[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mongodb', 'php82Extensions.pdo', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.fileinfo', 'php82Extensions.tokenizer', 'composer', 'nodejs_18', 'npm']

[phases.install]
cmds = ['composer install --ignore-platform-reqs']

[phases.build]
cmds = [
    'composer install --optimize-autoloader --no-dev --ignore-platform-reqs',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[phases.start]
cmd = 'php -S 0.0.0.0:$PORT -t public/'

[variables]
PHP_VERSION = '8.2'